### ISSUE TITLE
There was an unexpected internal error. Please try again. after successful login

### ISSUE THREAD

**Issue by robertforbes68** [okta/samples-js-angular#45] opened 2019-10-16 19:03 UTC
Pulled the project installed it with npm, configured it for my OKTA environment. Everything starts fine and the login page is rendered properly. The user is authenticated and it shows in the logs on the OKTA server that the user was successful. But then the application it pops an error saying There was an unexpected internal error. Please try again. and leaves me at the login page.

**Comment by swiftone** [comment] 2019-10-16 20:07
> But then the application it pops an error saying There was an unexpected internal error. Please try again. and leaves me at the login page.

I can't find the phrase "unexpected internal error" in the code for the samples-js-angular, the okta-angular library, or the okta-auth-js library.  Can you give a little more detail on what you're seeing?  Was this pop up in reaction to an action, or just while sitting there?  Was it immediate, or after a period of time (how much?)   Was this a pop up from the application code, from the browser, or from your system?

**Comment by swiftone** [comment] 2019-11-04 21:04
Closing this issue - if this remains a problem, feel free to reopen with the requested details.

**Closed by swiftone** 2019-11-04 21:04 UTC

**Comment by spirit-catcher** [comment] 2020-03-01 04:46
I have this very same issue.  

Mar 01 12:38:23 | Raymond Walker  (User) | User accessing Okta admin appsuccess | Raymond Walker  (AppUser)
-- | -- | -- | --

This shows I am successfully logging in to OKTA but my Website login box returns with There was an unexpected internal error. Please try again.

ANy Ideas on what could be the cause
